// This file was generated by Prisma
import { defineConfig } from "prisma/config";

// Get datasource URL from environment or use fallback
const datasourceUrl = process.env.DATABASE_URL || "file:./prisma/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
